In [1]:
from oemof import outputlib
from oemof import solph
import numpy as np
import pandas as pd
import xarray as xr

![](energysystem.png)

In [2]:
energysystem = solph.EnergySystem()
energysystem.restore(dpath='./', filename='energysystem.dump')
results = energysystem.results['main']

In [3]:
results

{("<oemof.solph.network.Bus: 'b_heat_source'>",
  "<oemof.solph.network.Transformer: 'heat_pump'>"): {'scalars': Series([], Name: 2016-01-01 00:00:00, dtype: float64),
  'sequences': variable_name            flow
  2016-01-01 00:00:00  3.918540
  2016-01-01 01:00:00  4.001186
  2016-01-01 02:00:00  4.184690
  2016-01-01 03:00:00  4.641344
  2016-01-01 04:00:00  5.800365
  2016-01-01 05:00:00  6.666667
  2016-01-01 06:00:00  6.666667
  2016-01-01 07:00:00  6.666667
  2016-01-01 08:00:00  6.666667
  2016-01-01 09:00:00  6.666667
  2016-01-01 10:00:00  6.666667
  2016-01-01 11:00:00  6.666667
  2016-01-01 12:00:00  6.495739
  2016-01-01 13:00:00  6.499551
  2016-01-01 14:00:00  6.580753
  2016-01-01 15:00:00  6.666667
  2016-01-01 16:00:00  6.666667
  2016-01-01 17:00:00  6.666667
  2016-01-01 18:00:00  6.666667
  2016-01-01 19:00:00  6.666667
  2016-01-01 20:00:00  6.666667
  2016-01-01 21:00:00  5.825812
  2016-01-01 22:00:00  4.019274
  2016-01-01 23:00:00  3.844627
  2016-01-02 00:00:00  4.606934
  2016-01-02 01:00:00  4.731963
  2016-01-02 02:00:00  4.932717
  2016-01-02 03:00:00  5.290059
  2016-01-02 04:00:00  6.224897
  2016-01-02 05:00:00  6.666667
  ...                       ...
  2016-01-09 18:00:00  6.666667
  2016-01-09 19:00:00  6.666667
  2016-01-09 20:00:00  6.666667
  2016-01-09 21:00:00  6.292904
  2016-01-09 22:00:00  4.516392
  2016-01-09 23:00:00  4.335244
  2016-01-10 00:00:00  3.079628
  2016-01-10 01:00:00  3.144580
  2016-01-10 02:00:00  3.288798
  2016-01-10 03:00:00  3.647688
  2016-01-10 04:00:00  4.558577
  2016-01-10 05:00:00  6.272976
  2016-01-10 06:00:00  6.666667
  2016-01-10 07:00:00  6.666667
  2016-01-10 08:00:00  6.417865
  2016-01-10 09:00:00  5.975580
  2016-01-10 10:00:00  5.511919
  2016-01-10 11:00:00  5.245636
  2016-01-10 12:00:00  5.105080
  2016-01-10 13:00:00  5.108075
  2016-01-10 14:00:00  5.171893
  2016-01-10 15:00:00  5.328843
  2016-01-10 16:00:00  5.606893
  2016-01-10 17:00:00  5.986914
  2016-01-10 18:00:00  6.230214
  2016-01-10 19:00:00  5.946724
  2016-01-10 20:00:00  5.505094
  2016-01-10 21:00:00  4.578576
  2016-01-10 22:00:00  3.158796
  2016-01-10 23:00:00  3.021539

  [240 rows x 1 columns]},
 ("<oemof.solph.network.Bus: 'bel'>",
  "<oemof.solph.network.Sink: 'demand_el'>"): {'scalars': Series([], Name: 2016-01-01 00:00:00, dtype: float64),
  'sequences': variable_name             flow
  2016-01-01 00:00:00  52.169653
  2016-01-01 01:00:00  52.169653
  2016-01-01 02:00:00  47.392644
  2016-01-01 03:00:00  45.197772
  2016-01-01 04:00:00  44.189789
  2016-01-01 05:00:00  42.397456
  2016-01-01 06:00:00  39.072422
  2016-01-01 07:00:00  38.786609
  2016-01-01 08:00:00  39.558959
  2016-01-01 09:00:00  42.074553
  2016-01-01 10:00:00  44.811597
  2016-01-01 11:00:00  48.223902
  2016-01-01 12:00:00  49.207885
  2016-01-01 13:00:00  48.234811
  2016-01-01 14:00:00  47.857363
  2016-01-01 15:00:00  47.914089
  2016-01-01 16:00:00  51.140943
  2016-01-01 17:00:00  56.369581
  2016-01-01 18:00:00  57.745194
  2016-01-01 19:00:00  56.860482
  2016-01-01 20:00:00  54.858698
  2016-01-01 21:00:00  54.772517
  2016-01-01 22:00:00  56.029223
  2016-01-01 23:00:00  52.417285
  2016-01-02 00:00:00  49.079160
  2016-01-02 01:00:00  47.256282
  2016-01-02 02:00:00  46.174119
  2016-01-02 03:00:00  45.731217
  2016-01-02 04:00:00  46.577748
  2016-01-02 05:00:00  48.655895
  ...                        ...
  2016-01-09 18:00:00  78.942285
  2016-01-09 19:00:00  77.106317
  2016-01-09 20:00:00  73.397289
  2016-01-09 21:00:00  71.044239
  2016-01-09 22:00:00  70.161708
  2016-01-09 23:00:00  66.427591
  2016-01-10 00:00:00  63.842180
  2016-01-10 01:00:00  62.590929
  2016-01-10 02:00:00  61.708399
  2016-01-10 03:00:00  60.840050
  2016-01-10 04:00:00  60.957866
  2016-01-10 05:00:00  61.111682
  2016-01-10 06:00:00  67.233759
  2016-01-10 07:00:00  74.925627
  2016-01-10 08:00:00  76.895775
  2016-01-10 09:00:00  76.229241
  2016-01-10 10:00:00  76.803049
  2016-01-10 11:00:00  77.489219
  2016-01-10 12:00:00  77.181588
  2016-01-10 13:00:00  76.647052
  2016-01-10 14:00:00  75.785249
  2016-01-10 15:00:00  75.144896
  2016-01-10 16:00:00  75.779794
  2016-01-10 17:00:00  79.880451
  2016-01-10 18:00:00  79.557548
  2016-01-10 19:00:00  77.437948
  2016-01-10 20:00:00  73.335109
  2016-01-10 21:00:00  71.402051
  2016-01-10 22:00:00  70.788970
  2016-01-10 23:00:00  66.811584

  [240 rows x 1 columns]},
 ("<oemof.solph.network.Bus: 'bel'>",
  "<oemof.solph.network.Sink: 'excess_el'>"): {'scalars': Series([], Name: 2016-01-01 00:00:00, dtype: float64),
  'sequences': variable_name             flow
  2016-01-01 00:00:00  44.704306
  2016-01-01 01:00:00  44.861883
  2016-01-01 02:00:00  49.679740
  2016-01-01 03:00:00  51.646285
  2016-01-01 04:00:00  50.019457
  2016-01-01 05:00:00  48.482340
  2016-01-01 06:00:00  53.452734
  2016-01-01 07:00:00  52.995635
  2016-01-01 08:00:00  52.056170
  2016-01-01 09:00:00  50.690154
  2016-01-01 10:00:00  70.453809
  2016-01-01 11:00:00  67.901029
  2016-01-01 12:00:00  64.223884
  2016-01-01 13:00:00  73.993832
  2016-01-01 14:00:00   2.448371
  2016-01-01 15:00:00   1.382580
  2016-01-01 16:00:00   7.843355
  2016-01-01 17:00:00   7.004101
  2016-01-01 18:00:00  78.621490
  2016-01-01 19:00:00   2.477670
  2016-01-01 20:00:00   3.780979
  2016-01-01 21:00:00   7.818977
  2016-01-01 22:00:00   8.261140
  2016-01-01 23:00:00   7.120502
  2016-01-02 00:00:00  13.856573
  2016-01-02 01:00:00  16.346236
  2016-01-02 02:00:00  16.399823
  2016-01-02 03:00:00  15.802153
  2016-01-02 04:00:00  16.344603
  2016-01-02 05:00:00   7.331517
  ...                        ...
  2016-01-09 18:00:00   0.000000
  2016-01-09 19:00:00   1.331214
  2016-01-09 20:00:00   4.434226
  2016-01-09 21:00:00   6.220685
  2016-01-09 22:00:00   7.991471
  2016-01-09 23:00:00  12.136127
  2016-01-10 00:00:00  15.350009
  2016-01-10 01:00:00  16.248157
  2016-01-10 02:00:00  17.058578
  2016-01-10 03:00:00  17.747482
  2016-01-10 04:00:00  17.174221
  2016-01-10 05:00:00  16.163206
  2016-01-10 06:00:00  10.694424
  2016-01-10 07:00:00   2.470798
  2016-01-10 08:00:00   0.949857
  2016-01-10 09:00:00   2.115008
  2016-01-10 10:00:00   2.040761
  2016-01-10 11:00:00   1.970349
  2016-01-10 12:00:00   2.185008
  2016-01-10 13:00:00   2.130950
  2016-01-10 14:00:00   2.634344
  2016-01-10 15:00:00   2.925880
  2016-01-10 16:00:00   1.818588
  2016-01-10 17:00:00   0.000000
  2016-01-10 18:00:00   0.000000
  2016-01-10 19:00:00   0.000000
  2016-01-10 20:00:00   4.314173
  2016-01-10 21:00:00   6.720037
  2016-01-10 22:00:00   8.043007
  2016-01-10 23:00:00  12.089022

  [240 rows x 1 columns]},
 ("<oemof.solph.network.Bus: 'bel'>",
  "<oemof.solph.network.Transformer: 'heat_pump'>"): {'scalars': Series([], Name: 2016-01-01 00:00:00, dtype: float64),
  'sequences': variable_name            flow
  2016-01-01 00:00:00  1.959270
  2016-01-01 01:00:00  2.000593
  2016-01-01 02:00:00  2.092345
  2016-01-01 03:00:00  2.320672
  2016-01-01 04:00:00  2.900182
  2016-01-01 05:00:00  3.333333
  2016-01-01 06:00:00  3.333333
  2016-01-01 07:00:00  3.333333
  2016-01-01 08:00:00  3.333333
  2016-01-01 09:00:00  3.333333
  2016-01-01 10:00:00  3.333333
  2016-01-01 11:00:00  3.333333
  2016-01-01 12:00:00  3.247870
  2016-01-01 13:00:00  3.249775
  2016-01-01 14:00:00  3.290377
  2016-01-01 15:00:00  3.333333
  2016-01-01 16:00:00  3.333333
  2016-01-01 17:00:00  3.333333
  2016-01-01 18:00:00  3.333333
  2016-01-01 19:00:00  3.333333
  2016-01-01 20:00:00  3.333333
  2016-01-01 21:00:00  2.912906
  2016-01-01 22:00:00  2.009637
  2016-01-01 23:00:00  1.922314
  2016-01-02 00:00:00  2.303467
  2016-01-02 01:00:00  2.365981
  2016-01-02 02:00:00  2.466359
  2016-01-02 03:00:00  2.645030
  2016-01-02 04:00:00  3.112449
  2016-01-02 05:00:00  3.333333
  ...                       ...
  2016-01-09 18:00:00  3.333333
  2016-01-09 19:00:00  3.333333
  2016-01-09 20:00:00  3.333333
  2016-01-09 21:00:00  3.146452
  2016-01-09 22:00:00  2.258196
  2016-01-09 23:00:00  2.167622
  2016-01-10 00:00:00  1.539814
  2016-01-10 01:00:00  1.572290
  2016-01-10 02:00:00  1.644399
  2016-01-10 03:00:00  1.823844
  2016-01-10 04:00:00  2.279288
  2016-01-10 05:00:00  3.136488
  2016-01-10 06:00:00  3.333333
  2016-01-10 07:00:00  3.333333
  2016-01-10 08:00:00  3.208933
  2016-01-10 09:00:00  2.987790
  2016-01-10 10:00:00  2.755960
  2016-01-10 11:00:00  2.622818
  2016-01-10 12:00:00  2.552540
  2016-01-10 13:00:00  2.554038
  2016-01-10 14:00:00  2.585947
  2016-01-10 15:00:00  2.664422
  2016-01-10 16:00:00  2.803447
  2016-01-10 17:00:00  2.993457
  2016-01-10 18:00:00  3.115107
  2016-01-10 19:00:00  2.973362
  2016-01-10 20:00:00  2.752547
  2016-01-10 21:00:00  2.289288
  2016-01-10 22:00:00  1.579398
  2016-01-10 23:00:00  1.510769

  [240 rows x 1 columns]},
 ("<oemof.solph.network.Bus: 'bth'>",
  "<oemof.solph.network.Sink: 'demand_th'>"): {'scalars': Series([], Name: 2016-01-01 00:00:00, dtype: float64),
  'sequences': variable_name             flow
  2016-01-01 00:00:00   5.877809
  2016-01-01 01:00:00   6.001778
  2016-01-01 02:00:00   6.277035
  2016-01-01 03:00:00   6.962015
  2016-01-01 04:00:00   8.700547
  2016-01-01 05:00:00  11.972667
  2016-01-01 06:00:00  14.166482
  2016-01-01 07:00:00  13.264331
  2016-01-01 08:00:00  12.249205
  2016-01-01 09:00:00  11.405055
  2016-01-01 10:00:00  10.520107
  2016-01-01 11:00:00  10.011875
  2016-01-01 12:00:00   9.743609
  2016-01-01 13:00:00   9.749326
  2016-01-01 14:00:00   9.871130
  2016-01-01 15:00:00  10.170686
  2016-01-01 16:00:00  10.701375
  2016-01-01 17:00:00  11.426687
  2016-01-01 18:00:00  11.891051
  2016-01-01 19:00:00  11.349979
  2016-01-01 20:00:00  10.507080
  2016-01-01 21:00:00   8.738718
  2016-01-01 22:00:00   6.028911
  2016-01-01 23:00:00   5.766941
  2016-01-02 00:00:00   6.910402
  2016-01-02 01:00:00   7.097944
  2016-01-02 02:00:00   7.399076
  2016-01-02 03:00:00   7.935089
  2016-01-02 04:00:00   9.337345
  2016-01-02 05:00:00  12.363126
  ...                        ...
  2016-01-09 18:00:00  12.249648
  2016-01-09 19:00:00  11.812651
  2016-01-09 20:00:00  11.017360
  2016-01-09 21:00:00   9.439357
  2016-01-09 22:00:00   6.774588
  2016-01-09 23:00:00   6.502866
  2016-01-10 00:00:00   4.619441
  2016-01-10 01:00:00   4.716870
  2016-01-10 02:00:00   4.933197
  2016-01-10 03:00:00   5.471532
  2016-01-10 04:00:00   6.837865
  2016-01-10 05:00:00   9.409464
  2016-01-10 06:00:00  11.133609
  2016-01-10 07:00:00  10.424598
  2016-01-10 08:00:00   9.626798
  2016-01-10 09:00:00   8.963370
  2016-01-10 10:00:00   8.267879
  2016-01-10 11:00:00   7.868453
  2016-01-10 12:00:00   7.657620
  2016-01-10 13:00:00   7.662113
  2016-01-10 14:00:00   7.757840
  2016-01-10 15:00:00   7.993265
  2016-01-10 16:00:00   8.410340
  2016-01-10 17:00:00   8.980371
  2016-01-10 18:00:00   9.345321
  2016-01-10 19:00:00   8.920086
  2016-01-10 20:00:00   8.257641
  2016-01-10 21:00:00   6.867864
  2016-01-10 22:00:00   4.738194
  2016-01-10 23:00:00   4.532308

  [240 rows x 1 columns]},
 ("<oemof.solph.network.Bus: 'coal'>",
  "<oemof.solph.network.Transformer: 'pp_coal'>"): {'scalars': Series([], Name: 2016-01-01 00:00:00, dtype: float64),
  'sequences': variable_name        flow
  2016-01-01 00:00:00   0.0
  2016-01-01 01:00:00   0.0
  2016-01-01 02:00:00   0.0
  2016-01-01 03:00:00   0.0
  2016-01-01 04:00:00   0.0
  2016-01-01 05:00:00   0.0
  2016-01-01 06:00:00   0.0
  2016-01-01 07:00:00   0.0
  2016-01-01 08:00:00   0.0
  2016-01-01 09:00:00   0.0
  2016-01-01 10:00:00   0.0
  2016-01-01 11:00:00   0.0
  2016-01-01 12:00:00   0.0
  2016-01-01 13:00:00   0.0
  2016-01-01 14:00:00   0.0
  2016-01-01 15:00:00   0.0
  2016-01-01 16:00:00   0.0
  2016-01-01 17:00:00   0.0
  2016-01-01 18:00:00   0.0
  2016-01-01 19:00:00   0.0
  2016-01-01 20:00:00   0.0
  2016-01-01 21:00:00   0.0
  2016-01-01 22:00:00   0.0
  2016-01-01 23:00:00   0.0
  2016-01-02 00:00:00   0.0
  2016-01-02 01:00:00   0.0
  2016-01-02 02:00:00   0.0
  2016-01-02 03:00:00   0.0
  2016-01-02 04:00:00   0.0
  2016-01-02 05:00:00   0.0
  ...                   ...
  2016-01-09 18:00:00   0.0
  2016-01-09 19:00:00   0.0
  2016-01-09 20:00:00   0.0
  2016-01-09 21:00:00   0.0
  2016-01-09 22:00:00   0.0
  2016-01-09 23:00:00   0.0
  2016-01-10 00:00:00   0.0
  2016-01-10 01:00:00   0.0
  2016-01-10 02:00:00   0.0
  2016-01-10 03:00:00   0.0
  2016-01-10 04:00:00   0.0
  2016-01-10 05:00:00   0.0
  2016-01-10 06:00:00   0.0
  2016-01-10 07:00:00   0.0
  2016-01-10 08:00:00   0.0
  2016-01-10 09:00:00   0.0
  2016-01-10 10:00:00   0.0
  2016-01-10 11:00:00   0.0
  2016-01-10 12:00:00   0.0
  2016-01-10 13:00:00   0.0
  2016-01-10 14:00:00   0.0
  2016-01-10 15:00:00   0.0
  2016-01-10 16:00:00   0.0
  2016-01-10 17:00:00   0.0
  2016-01-10 18:00:00   0.0
  2016-01-10 19:00:00   0.0
  2016-01-10 20:00:00   0.0
  2016-01-10 21:00:00   0.0
  2016-01-10 22:00:00   0.0
  2016-01-10 23:00:00   0.0

  [240 rows x 1 columns]},
 ("<oemof.solph.network.Bus: 'gas'>",
  "<oemof.solph.network.Transformer: 'pp_chp'>"): {'scalars': Series([], Name: 2016-01-01 00:00:00, dtype: float64),
  'sequences': variable_name             flow
  2016-01-01 00:00:00  -0.000000
  2016-01-01 01:00:00  -0.000000
  2016-01-01 02:00:00  -0.000000
  2016-01-01 03:00:00  -0.000000
  2016-01-01 04:00:00  -0.000000
  2016-01-01 05:00:00   4.931668
  2016-01-01 06:00:00  10.416204
  2016-01-01 07:00:00   8.160828
  2016-01-01 08:00:00   5.623012
  2016-01-01 09:00:00   3.512637
  2016-01-01 10:00:00   1.300267
  2016-01-01 11:00:00   0.029687
  2016-01-01 12:00:00  -0.000000
  2016-01-01 13:00:00  -0.000000
  2016-01-01 14:00:00  -0.000000
  2016-01-01 15:00:00   0.426715
  2016-01-01 16:00:00   1.753438
  2016-01-01 17:00:00   3.566716
  2016-01-01 18:00:00   4.727627
  2016-01-01 19:00:00   3.374948
  2016-01-01 20:00:00   1.267700
  2016-01-01 21:00:00  -0.000000
  2016-01-01 22:00:00  -0.000000
  2016-01-01 23:00:00  -0.000000
  2016-01-02 00:00:00  -0.000000
  2016-01-02 01:00:00  -0.000000
  2016-01-02 02:00:00  -0.000000
  2016-01-02 03:00:00  -0.000000
  2016-01-02 04:00:00  -0.000000
  2016-01-02 05:00:00   5.907815
  ...                        ...
  2016-01-09 18:00:00   5.624121
  2016-01-09 19:00:00   4.531629
  2016-01-09 20:00:00   2.543400
  2016-01-09 21:00:00  -0.000000
  2016-01-09 22:00:00  -0.000000
  2016-01-09 23:00:00  -0.000000
  2016-01-10 00:00:00  -0.000000
  2016-01-10 01:00:00  -0.000000
  2016-01-10 02:00:00  -0.000000
  2016-01-10 03:00:00  -0.000000
  2016-01-10 04:00:00  -0.000000
  2016-01-10 05:00:00  -0.000000
  2016-01-10 06:00:00   2.834023
  2016-01-10 07:00:00   1.061495
  2016-01-10 08:00:00  -0.000000
  2016-01-10 09:00:00  -0.000000
  2016-01-10 10:00:00  -0.000000
  2016-01-10 11:00:00  -0.000000
  2016-01-10 12:00:00  -0.000000
  2016-01-10 13:00:00  -0.000000
  2016-01-10 14:00:00  -0.000000
  2016-01-10 15:00:00  -0.000000
  2016-01-10 16:00:00  -0.000000
  2016-01-10 17:00:00  -0.000000
  2016-01-10 18:00:00  -0.000000
  2016-01-10 19:00:00  -0.000000
  2016-01-10 20:00:00  -0.000000
  2016-01-10 21:00:00  -0.000000
  2016-01-10 22:00:00  -0.000000
  2016-01-10 23:00:00  -0.000000

  [240 rows x 1 columns]},
 ("<oemof.solph.network.Bus: 'gas'>",
  "<oemof.solph.network.Transformer: 'pp_gas'>"): {'scalars': Series([], Name: 2016-01-01 00:00:00, dtype: float64),
  'sequences': variable_name        flow
  2016-01-01 00:00:00   0.0
  2016-01-01 01:00:00   0.0
  2016-01-01 02:00:00   0.0
  2016-01-01 03:00:00   0.0
  2016-01-01 04:00:00   0.0
  2016-01-01 05:00:00   0.0
  2016-01-01 06:00:00   0.0
  2016-01-01 07:00:00   0.0
  2016-01-01 08:00:00   0.0
  2016-01-01 09:00:00   0.0
  2016-01-01 10:00:00   0.0
  2016-01-01 11:00:00   0.0
  2016-01-01 12:00:00   0.0
  2016-01-01 13:00:00   0.0
  2016-01-01 14:00:00   0.0
  2016-01-01 15:00:00   0.0
  2016-01-01 16:00:00   0.0
  2016-01-01 17:00:00   0.0
  2016-01-01 18:00:00   0.0
  2016-01-01 19:00:00   0.0
  2016-01-01 20:00:00   0.0
  2016-01-01 21:00:00   0.0
  2016-01-01 22:00:00   0.0
  2016-01-01 23:00:00   0.0
  2016-01-02 00:00:00   0.0
  2016-01-02 01:00:00   0.0
  2016-01-02 02:00:00   0.0
  2016-01-02 03:00:00   0.0
  2016-01-02 04:00:00   0.0
  2016-01-02 05:00:00   0.0
  ...                   ...
  2016-01-09 18:00:00   0.0
  2016-01-09 19:00:00   0.0
  2016-01-09 20:00:00   0.0
  2016-01-09 21:00:00   0.0
  2016-01-09 22:00:00   0.0
  2016-01-09 23:00:00   0.0
  2016-01-10 00:00:00   0.0
  2016-01-10 01:00:00   0.0
  2016-01-10 02:00:00   0.0
  2016-01-10 03:00:00   0.0
  2016-01-10 04:00:00   0.0
  2016-01-10 05:00:00   0.0
  2016-01-10 06:00:00   0.0
  2016-01-10 07:00:00   0.0
  2016-01-10 08:00:00   0.0
  2016-01-10 09:00:00   0.0
  2016-01-10 10:00:00   0.0
  2016-01-10 11:00:00   0.0
  2016-01-10 12:00:00   0.0
  2016-01-10 13:00:00   0.0
  2016-01-10 14:00:00   0.0
  2016-01-10 15:00:00   0.0
  2016-01-10 16:00:00   0.0
  2016-01-10 17:00:00   0.0
  2016-01-10 18:00:00   0.0
  2016-01-10 19:00:00   0.0
  2016-01-10 20:00:00   0.0
  2016-01-10 21:00:00   0.0
  2016-01-10 22:00:00   0.0
  2016-01-10 23:00:00   0.0

  [240 rows x 1 columns]},
 ("<oemof.solph.network.Transformer: 'heat_pump'>",
  "<oemof.solph.network.Bus: 'bth'>"): {'scalars': Series([], Name: 2016-01-01 00:00:00, dtype: float64),
  'sequences': variable_name             flow
  2016-01-01 00:00:00   5.877809
  2016-01-01 01:00:00   6.001779
  2016-01-01 02:00:00   6.277035
  2016-01-01 03:00:00   6.962015
  2016-01-01 04:00:00   8.700547
  2016-01-01 05:00:00  10.000000
  2016-01-01 06:00:00  10.000000
  2016-01-01 07:00:00  10.000000
  2016-01-01 08:00:00  10.000000
  2016-01-01 09:00:00  10.000000
  2016-01-01 10:00:00  10.000000
  2016-01-01 11:00:00  10.000000
  2016-01-01 12:00:00   9.743609
  2016-01-01 13:00:00   9.749326
  2016-01-01 14:00:00   9.871130
  2016-01-01 15:00:00  10.000000
  2016-01-01 16:00:00  10.000000
  2016-01-01 17:00:00  10.000000
  2016-01-01 18:00:00  10.000000
  2016-01-01 19:00:00  10.000000
  2016-01-01 20:00:00  10.000000
  2016-01-01 21:00:00   8.738718
  2016-01-01 22:00:00   6.028911
  2016-01-01 23:00:00   5.766941
  2016-01-02 00:00:00   6.910401
  2016-01-02 01:00:00   7.097944
  2016-01-02 02:00:00   7.399076
  2016-01-02 03:00:00   7.935088
  2016-01-02 04:00:00   9.337345
  2016-01-02 05:00:00  10.000000
  ...                        ...
  2016-01-09 18:00:00  10.000000
  2016-01-09 19:00:00  10.000000
  2016-01-09 20:00:00  10.000000
  2016-01-09 21:00:00   9.439357
  2016-01-09 22:00:00   6.774588
  2016-01-09 23:00:00   6.502866
  2016-01-10 00:00:00   4.619441
  2016-01-10 01:00:00   4.716870
  2016-01-10 02:00:00   4.933197
  2016-01-10 03:00:00   5.471532
  2016-01-10 04:00:00   6.837865
  2016-01-10 05:00:00   9.409464
  2016-01-10 06:00:00  10.000000
  2016-01-10 07:00:00  10.000000
  2016-01-10 08:00:00   9.626798
  2016-01-10 09:00:00   8.963370
  2016-01-10 10:00:00   8.267879
  2016-01-10 11:00:00   7.868453
  2016-01-10 12:00:00   7.657620
  2016-01-10 13:00:00   7.662113
  2016-01-10 14:00:00   7.757840
  2016-01-10 15:00:00   7.993265
  2016-01-10 16:00:00   8.410340
  2016-01-10 17:00:00   8.980371
  2016-01-10 18:00:00   9.345320
  2016-01-10 19:00:00   8.920086
  2016-01-10 20:00:00   8.257641
  2016-01-10 21:00:00   6.867864
  2016-01-10 22:00:00   4.738194
  2016-01-10 23:00:00   4.532308

  [240 rows x 1 columns]},
 ("<oemof.solph.network.Source: 'heat_source'>",
  "<oemof.solph.network.Bus: 'b_heat_source'>"): {'scalars': Series([], Name: 2016-01-01 00:00:00, dtype: float64),
  'sequences': variable_name            flow
  2016-01-01 00:00:00  3.918540
  2016-01-01 01:00:00  4.001186
  2016-01-01 02:00:00  4.184690
  2016-01-01 03:00:00  4.641344
  2016-01-01 04:00:00  5.800365
  2016-01-01 05:00:00  6.666667
  2016-01-01 06:00:00  6.666667
  2016-01-01 07:00:00  6.666667
  2016-01-01 08:00:00  6.666667
  2016-01-01 09:00:00  6.666667

# Option in outputlib.views.node: Dataframe or multiindex dataframe

In [8]:
timeseries_multiindex = outputlib.views.node(results, 'pp_oil', multiindex=True)['sequences']
timeseries_multiindex.head()

from                       oil     pp_oil
to                      pp_oil        bel
type                      flow       flow
2016-01-01 00:00:00  287.14939  80.401829
2016-01-01 01:00:00  287.14939  80.401829
2016-01-01 02:00:00  287.14939  80.401829
2016-01-01 03:00:00  287.14939  80.401829
2016-01-01 04:00:00  287.14939  80.401829

In [9]:
timeseries = outputlib.views.node(results, 'pp_oil')['sequences']
timeseries.head()

                     ((oil, pp_oil), flow)  ((pp_oil, bel), flow)
2016-01-01 00:00:00              287.14939              80.401829
2016-01-01 01:00:00              287.14939              80.401829
2016-01-01 02:00:00              287.14939              80.401829
2016-01-01 03:00:00              287.14939              80.401829
2016-01-01 04:00:00              287.14939              80.401829

# Why not have a function to output all data as one big dataframe?

## All sequences with tuple indices

In [10]:
string_results = outputlib.processing.convert_keys_to_strings(results)

In [11]:
all_sequences = [value['sequences'].rename(columns={'flow': key}) for (key, value) in string_results.items()]
all_sequences = pd.concat(all_sequences, axis=1)
all_sequences.head()

variable_name,"(b_heat_source, heat_pump)","(bel, demand_el)","(bel, excess_el)","(bel, heat_pump)","(bth, demand_th)","(coal, pp_coal)","(gas, pp_chp)","(gas, pp_gas)","(heat_pump, bth)","(heat_source, b_heat_source)","(lignite, pp_lig)","(oil, pp_oil)","(pp_chp, bel)","(pp_chp, bth)","(pp_coal, bel)","(pp_gas, bel)","(pp_lig, bel)","(pp_oil, bel)","(pv, bel)","(wind, bel)"
2016-01-01 00:00:00,3.918540,52.169653,44.704306,1.959270,5.877809,0.0,-0.0,0.0,5.877809,3.918540,0.0,287.14939,0.0,0.0,0.0,0.0,0.0,80.401829,0.0,18.4314
2016-01-01 01:00:00,4.001186,52.169653,44.861883,2.000593,6.001778,0.0,-0.0,0.0,6.001779,4.001186,0.0,287.14939,0.0,0.0,0.0,0.0,0.0,80.401829,0.0,18.6303
2016-01-01 02:00:00,4.184690,47.392644,49.679740,2.092345,6.277035,0.0,-0.0,0.0,6.277035,4.184690,0.0,287.14939,0.0,0.0,0.0,0.0,0.0,80.401829,0.0,18.7629
2016-01-01 03:00:00,4.641344,45.197772,51.646285,2.320672,6.962015,0.0,-0.0,0.0,6.962015,4.641344,0.0,287.14939,0.0,0.0,0.0,0.0,0.0,80.401829,0.0,18.7629
2016-01-01 04:00:00,5.800365,44.189789,50.019457,2.900182,8.700547,0.0,-0.0,0.0,8.700547,5.800365,0.0,287.14939,0.0,0.0,0.0,0.0,0.0,80.401829,0.0,16.7076

## All sequences with multiindex

In [12]:
all_sequences = [value['sequences'].rename(columns={'flow': key}) for (key, value) in string_results.items()]
all_sequences = pd.concat(all_sequences, axis=1)
tuples = [key for (key, value) in string_results.items()]
multi_index = pd.MultiIndex.from_tuples(tuples, names=['from', 'to'])
all_sequences.columns = multi_index
all_sequences.head()

from                b_heat_source        bel                            bth  \
to                      heat_pump  demand_el  excess_el heat_pump demand_th
2016-01-01 00:00:00      3.918540  52.169653  44.704306  1.959270  5.877809
2016-01-01 01:00:00      4.001186  52.169653  44.861883  2.000593  6.001778
2016-01-01 02:00:00      4.184690  47.392644  49.679740  2.092345  6.277035
2016-01-01 03:00:00      4.641344  45.197772  51.646285  2.320672  6.962015
2016-01-01 04:00:00      5.800365  44.189789  50.019457  2.900182  8.700547

from                   coal    gas        heat_pump   heat_source lignite  \
to                  pp_coal pp_chp pp_gas       bth b_heat_source  pp_lig
2016-01-01 00:00:00     0.0   -0.0    0.0  5.877809      3.918540     0.0
2016-01-01 01:00:00     0.0   -0.0    0.0  6.001779      4.001186     0.0
2016-01-01 02:00:00     0.0   -0.0    0.0  6.277035      4.184690     0.0
2016-01-01 03:00:00     0.0   -0.0    0.0  6.962015      4.641344     0.0
2016-01-01 04:00:00     0.0   -0.0    0.0  8.700547      5.800365     0.0

from                       oil pp_chp      pp_coal pp_gas pp_lig     pp_oil  \
to                      pp_oil    bel  bth     bel    bel    bel        bel
2016-01-01 00:00:00  287.14939    0.0  0.0     0.0    0.0    0.0  80.401829
2016-01-01 01:00:00  287.14939    0.0  0.0     0.0    0.0    0.0  80.401829
2016-01-01 02:00:00  287.14939    0.0  0.0     0.0    0.0    0.0  80.401829
2016-01-01 03:00:00  287.14939    0.0  0.0     0.0    0.0    0.0  80.401829
2016-01-01 04:00:00  287.14939    0.0  0.0     0.0    0.0    0.0  80.401829

from                  pv     wind
to                   bel      bel
2016-01-01 00:00:00  0.0  18.4314
2016-01-01 01:00:00  0.0  18.6303
2016-01-01 02:00:00  0.0  18.7629
2016-01-01 03:00:00  0.0  18.7629
2016-01-01 04:00:00  0.0  16.7076

### Nice to filter:

In [13]:
all_sequences['bel', 'demand_el'].head()

2016-01-01 00:00:00    52.169653
2016-01-01 01:00:00    52.169653
2016-01-01 02:00:00    47.392644
2016-01-01 03:00:00    45.197772
2016-01-01 04:00:00    44.189789
Freq: H, Name: (bel, demand_el), dtype: float64

## All scalars

In [14]:
string_results

{('b_heat_source',
  'heat_pump'): {'scalars': Series([], Name: 2016-01-01 00:00:00, dtype: float64), 'sequences': variable_name            flow
  2016-01-01 00:00:00  3.918540
  2016-01-01 01:00:00  4.001186
  2016-01-01 02:00:00  4.184690
  2016-01-01 03:00:00  4.641344
  2016-01-01 04:00:00  5.800365
  2016-01-01 05:00:00  6.666667
  2016-01-01 06:00:00  6.666667
  2016-01-01 07:00:00  6.666667
  2016-01-01 08:00:00  6.666667
  2016-01-01 09:00:00  6.666667
  2016-01-01 10:00:00  6.666667
  2016-01-01 11:00:00  6.666667
  2016-01-01 12:00:00  6.495739
  2016-01-01 13:00:00  6.499551
  2016-01-01 14:00:00  6.580753
  2016-01-01 15:00:00  6.666667
  2016-01-01 16:00:00  6.666667
  2016-01-01 17:00:00  6.666667
  2016-01-01 18:00:00  6.666667
  2016-01-01 19:00:00  6.666667
  2016-01-01 20:00:00  6.666667
  2016-01-01 21:00:00  5.825812
  2016-01-01 22:00:00  4.019274
  2016-01-01 23:00:00  3.844627
  2016-01-02 00:00:00  4.606934
  2016-01-02 01:00:00  4.731963
  2016-01-02 02:00:00  4.932717
  2016-01-02 03:00:00  5.290059
  2016-01-02 04:00:00  6.224897
  2016-01-02 05:00:00  6.666667
  ...                       ...
  2016-01-09 18:00:00  6.666667
  2016-01-09 19:00:00  6.666667
  2016-01-09 20:00:00  6.666667
  2016-01-09 21:00:00  6.292904
  2016-01-09 22:00:00  4.516392
  2016-01-09 23:00:00  4.335244
  2016-01-10 00:00:00  3.079628
  2016-01-10 01:00:00  3.144580
  2016-01-10 02:00:00  3.288798
  2016-01-10 03:00:00  3.647688
  2016-01-10 04:00:00  4.558577
  2016-01-10 05:00:00  6.272976
  2016-01-10 06:00:00  6.666667
  2016-01-10 07:00:00  6.666667
  2016-01-10 08:00:00  6.417865
  2016-01-10 09:00:00  5.975580
  2016-01-10 10:00:00  5.511919
  2016-01-10 11:00:00  5.245636
  2016-01-10 12:00:00  5.105080
  2016-01-10 13:00:00  5.108075
  2016-01-10 14:00:00  5.171893
  2016-01-10 15:00:00  5.328843
  2016-01-10 16:00:00  5.606893
  2016-01-10 17:00:00  5.986914
  2016-01-10 18:00:00  6.230214
  2016-01-10 19:00:00  5.946724
  2016-01-10 20:00:00  5.505094
  2016-01-10 21:00:00  4.578576
  2016-01-10 22:00:00  3.158796
  2016-01-10 23:00:00  3.021539

  [240 rows x 1 columns]},
 ('bel',
  'demand_el'): {'scalars': Series([], Name: 2016-01-01 00:00:00, dtype: float64), 'sequences': variable_name             flow
  2016-01-01 00:00:00  52.169653
  2016-01-01 01:00:00  52.169653
  2016-01-01 02:00:00  47.392644
  2016-01-01 03:00:00  45.197772
  2016-01-01 04:00:00  44.189789
  2016-01-01 05:00:00  42.397456
  2016-01-01 06:00:00  39.072422
  2016-01-01 07:00:00  38.786609
  2016-01-01 08:00:00  39.558959
  2016-01-01 09:00:00  42.074553
  2016-01-01 10:00:00  44.811597
  2016-01-01 11:00:00  48.223902
  2016-01-01 12:00:00  49.207885
  2016-01-01 13:00:00  48.234811
  2016-01-01 14:00:00  47.857363
  2016-01-01 15:00:00  47.914089
  2016-01-01 16:00:00  51.140943
  2016-01-01 17:00:00  56.369581
  2016-01-01 18:00:00  57.745194
  2016-01-01 19:00:00  56.860482
  2016-01-01 20:00:00  54.858698
  2016-01-01 21:00:00  54.772517
  2016-01-01 22:00:00  56.029223
  2016-01-01 23:00:00  52.417285
  2016-01-02 00:00:00  49.079160
  2016-01-02 01:00:00  47.256282
  2016-01-02 02:00:00  46.174119
  2016-01-02 03:00:00  45.731217
  2016-01-02 04:00:00  46.577748
  2016-01-02 05:00:00  48.655895
  ...                        ...
  2016-01-09 18:00:00  78.942285
  2016-01-09 19:00:00  77.106317
  2016-01-09 20:00:00  73.397289
  2016-01-09 21:00:00  71.044239
  2016-01-09 22:00:00  70.161708
  2016-01-09 23:00:00  66.427591
  2016-01-10 00:00:00  63.842180
  2016-01-10 01:00:00  62.590929
  2016-01-10 02:00:00  61.708399
  2016-01-10 03:00:00  60.840050
  2016-01-10 04:00:00  60.957866
  2016-01-10 05:00:00  61.111682
  2016-01-10 06:00:00  67.233759
  2016-01-10 07:00:00  74.925627
  2016-01-10 08:00:00  76.895775
  2016-01-10 09:00:00  76.229241
  2016-01-10 10:00:00  76.803049
  2016-01-10 11:00:00  77.489219
  2016-01-10 12:00:00  77.181588
  2016-01-10 13:00:00  76.647052
  2016-01-10 14:00:00  75.785249
  2016-01-10 15:00:00  75.144896
  2016-01-10 16:00:00  75.779794
  2016-01-10 17:00:00  79.880451
  2016-01-10 18:00:00  79.557548
  2016-01-10 19:00:00  77.437948
  2016-01-10 20:00:00  73.335109
  2016-01-10 21:00:00  71.402051
  2016-01-10 22:00:00  70.788970
  2016-01-10 23:00:00  66.811584

  [240 rows x 1 columns]},
 ('bel',
  'excess_el'): {'scalars': Series([], Name: 2016-01-01 00:00:00, dtype: float64), 'sequences': variable_name             flow
  2016-01-01 00:00:00  44.704306
  2016-01-01 01:00:00  44.861883
  2016-01-01 02:00:00  49.679740
  2016-01-01 03:00:00  51.646285
  2016-01-01 04:00:00  50.019457
  2016-01-01 05:00:00  48.482340
  2016-01-01 06:00:00  53.452734
  2016-01-01 07:00:00  52.995635
  2016-01-01 08:00:00  52.056170
  2016-01-01 09:00:00  50.690154
  2016-01-01 10:00:00  70.453809
  2016-01-01 11:00:00  67.901029
  2016-01-01 12:00:00  64.223884
  2016-01-01 13:00:00  73.993832
  2016-01-01 14:00:00   2.448371
  2016-01-01 15:00:00   1.382580
  2016-01-01 16:00:00   7.843355
  2016-01-01 17:00:00   7.004101
  2016-01-01 18:00:00  78.621490
  2016-01-01 19:00:00   2.477670
  2016-01-01 20:00:00   3.780979
  2016-01-01 21:00:00   7.818977
  2016-01-01 22:00:00   8.261140
  2016-01-01 23:00:00   7.120502
  2016-01-02 00:00:00  13.856573
  2016-01-02 01:00:00  16.346236
  2016-01-02 02:00:00  16.399823
  2016-01-02 03:00:00  15.802153
  2016-01-02 04:00:00  16.344603
  2016-01-02 05:00:00   7.331517
  ...                        ...
  2016-01-09 18:00:00   0.000000
  2016-01-09 19:00:00   1.331214
  2016-01-09 20:00:00   4.434226
  2016-01-09 21:00:00   6.220685
  2016-01-09 22:00:00   7.991471
  2016-01-09 23:00:00  12.136127
  2016-01-10 00:00:00  15.350009
  2016-01-10 01:00:00  16.248157
  2016-01-10 02:00:00  17.058578
  2016-01-10 03:00:00  17.747482
  2016-01-10 04:00:00  17.174221
  2016-01-10 05:00:00  16.163206
  2016-01-10 06:00:00  10.694424
  2016-01-10 07:00:00   2.470798
  2016-01-10 08:00:00   0.949857
  2016-01-10 09:00:00   2.115008
  2016-01-10 10:00:00   2.040761
  2016-01-10 11:00:00   1.970349
  2016-01-10 12:00:00   2.185008
  2016-01-10 13:00:00   2.130950
  2016-01-10 14:00:00   2.634344
  2016-01-10 15:00:00   2.925880
  2016-01-10 16:00:00   1.818588
  2016-01-10 17:00:00   0.000000
  2016-01-10 18:00:00   0.000000
  2016-01-10 19:00:00   0.000000
  2016-01-10 20:00:00   4.314173
  2016-01-10 21:00:00   6.720037
  2016-01-10 22:00:00   8.043007
  2016-01-10 23:00:00  12.089022

  [240 rows x 1 columns]},
 ('bel',
  'heat_pump'): {'scalars': Series([], Name: 2016-01-01 00:00:00, dtype: float64), 'sequences': variable_name            flow
  2016-01-01 00:00:00  1.959270
  2016-01-01 01:00:00  2.000593
  2016-01-01 02:00:00  2.092345
  2016-01-01 03:00:00  2.320672
  2016-01-01 04:00:00  2.900182
  2016-01-01 05:00:00  3.333333
  2016-01-01 06:00:00  3.333333
  2016-01-01 07:00:00  3.333333
  2016-01-01 08:00:00  3.333333
  2016-01-01 09:00:00  3.333333
  2016-01-01 10:00:00  3.333333
  2016-01-01 11:00:00  3.333333
  2016-01-01 12:00:00  3.247870
  2016-01-01 13:00:00  3.249775
  2016-01-01 14:00:00  3.290377
  2016-01-01 15:00:00  3.333333
  2016-01-01 16:00:00  3.333333
  2016-01-01 17:00:00  3.333333
  2016-01-01 18:00:00  3.333333
  2016-01-01 19:00:00  3.333333
  2016-01-01 20:00:00  3.333333
  2016-01-01 21:00:00  2.912906
  2016-01-01 22:00:00  2.009637
  2016-01-01 23:00:00  1.922314
  2016-01-02 00:00:00  2.303467
  2016-01-02 01:00:00  2.365981
  2016-01-02 02:00:00  2.466359
  2016-01-02 03:00:00  2.645030
  2016-01-02 04:00:00  3.112449
  2016-01-02 05:00:00  3.333333
  ...                       ...
  2016-01-09 18:00:00  3.333333
  2016-01-09 19:00:00  3.333333
  2016-01-09 20:00:00  3.333333
  2016-01-09 21:00:00  3.146452
  2016-01-09 22:00:00  2.258196
  2016-01-09 23:00:00  2.167622
  2016-01-10 00:00:00  1.539814
  2016-01-10 01:00:00  1.572290
  2016-01-10 02:00:00  1.644399
  2016-01-10 03:00:00  1.823844
  2016-01-10 04:00:00  2.279288
  2016-01-10 05:00:00  3.136488
  2016-01-10 06:00:00  3.333333
  2016-01-10 07:00:00  3.333333
  2016-01-10 08:00:00  3.208933
  2016-01-10 09:00:00  2.987790
  2016-01-10 10:00:00  2.755960
  2016-01-10 11:00:00  2.622818
  2016-01-10 12:00:00  2.552540
  2016-01-10 13:00:00  2.554038
  2016-01-10 14:00:00  2.585947
  2016-01-10 15:00:00  2.664422
  2016-01-10 16:00:00  2.803447
  2016-01-10 17:00:00  2.993457
  2016-01-10 18:00:00  3.115107
  2016-01-10 19:00:00  2.973362
  2016-01-10 20:00:00  2.752547
  2016-01-10 21:00:00  2.289288
  2016-01-10 22:00:00  1.579398
  2016-01-10 23:00:00  1.510769

  [240 rows x 1 columns]},
 ('bth',
  'demand_th'): {'scalars': Series([], Name: 2016-01-01 00:00:00, dtype: float64), 'sequences': variable_name             flow
  2016-01-01 00:00:00   5.877809
  2016-01-01 01:00:00   6.001778
  2016-01-01 02:00:00   6.277035
  2016-01-01 03:00:00   6.962015
  2016-01-01 04:00:00   8.700547
  2016-01-01 05:00:00  11.972667
  2016-01-01 06:00:00  14.166482
  2016-01-01 07:00:00  13.264331
  2016-01-01 08:00:00  12.249205
  2016-01-01 09:00:00  11.405055
  2016-01-01 10:00:00  10.520107
  2016-01-01 11:00:00  10.011875
  2016-01-01 12:00:00   9.743609
  2016-01-01 13:00:00   9.749326
  2016-01-01 14:00:00   9.871130
  2016-01-01 15:00:00  10.170686
  2016-01-01 16:00:00  10.701375
  2016-01-01 17:00:00  11.426687
  2016-01-01 18:00:00  11.891051
  2016-01-01 19:00:00  11.349979
  2016-01-01 20:00:00  10.507080
  2016-01-01 21:00:00   8.738718
  2016-01-01 22:00:00   6.028911
  2016-01-01 23:00:00   5.766941
  2016-01-02 00:00:00   6.910402
  2016-01-02 01:00:00   7.097944
  2016-01-02 02:00:00   7.399076
  2016-01-02 03:00:00   7.935089
  2016-01-02 04:00:00   9.337345
  2016-01-02 05:00:00  12.363126
  ...                        ...
  2016-01-09 18:00:00  12.249648
  2016-01-09 19:00:00  11.812651
  2016-01-09 20:00:00  11.017360
  2016-01-09 21:00:00   9.439357
  2016-01-09 22:00:00   6.774588
  2016-01-09 23:00:00   6.502866
  2016-01-10 00:00:00   4.619441
  2016-01-10 01:00:00   4.716870
  2016-01-10 02:00:00   4.933197
  2016-01-10 03:00:00   5.471532
  2016-01-10 04:00:00   6.837865
  2016-01-10 05:00:00   9.409464
  2016-01-10 06:00:00  11.133609
  2016-01-10 07:00:00  10.424598
  2016-01-10 08:00:00   9.626798
  2016-01-10 09:00:00   8.963370
  2016-01-10 10:00:00   8.267879
  2016-01-10 11:00:00   7.868453
  2016-01-10 12:00:00   7.657620
  2016-01-10 13:00:00   7.662113
  2016-01-10 14:00:00   7.757840
  2016-01-10 15:00:00   7.993265
  2016-01-10 16:00:00   8.410340
  2016-01-10 17:00:00   8.980371
  2016-01-10 18:00:00   9.345321
  2016-01-10 19:00:00   8.920086
  2016-01-10 20:00:00   8.257641
  2016-01-10 21:00:00   6.867864
  2016-01-10 22:00:00   4.738194
  2016-01-10 23:00:00   4.532308

  [240 rows x 1 columns]},
 ('coal',
  'pp_coal'): {'scalars': Series([], Name: 2016-01-01 00:00:00, dtype: float64), 'sequences': variable_name        flow
  2016-01-01 00:00:00   0.0
  2016-01-01 01:00:00   0.0
  2016-01-01 02:00:00   0.0
  2016-01-01 03:00:00   0.0
  2016-01-01 04:00:00   0.0
  2016-01-01 05:00:00   0.0
  2016-01-01 06:00:00   0.0
  2016-01-01 07:00:00   0.0
  2016-01-01 08:00:00   0.0
  2016-01-01 09:00:00   0.0
  2016-01-01 10:00:00   0.0
  2016-01-01 11:00:00   0.0
  2016-01-01 12:00:00   0.0
  2016-01-01 13:00:00   0.0
  2016-01-01 14:00:00   0.0
  2016-01-01 15:00:00   0.0
  2016-01-01 16:00:00   0.0
  2016-01-01 17:00:00   0.0
  2016-01-01 18:00:00   0.0
  2016-01-01 19:00:00   0.0
  2016-01-01 20:00:00   0.0
  2016-01-01 21:00:00   0.0
  2016-01-01 22:00:00   0.0
  2016-01-01 23:00:00   0.0
  2016-01-02 00:00:00   0.0
  2016-01-02 01:00:00   0.0
  2016-01-02 02:00:00   0.0
  2016-01-02 03:00:00   0.0
  2016-01-02 04:00:00   0.0
  2016-01-02 05:00:00   0.0
  ...                   ...
  2016-01-09 18:00:00   0.0
  2016-01-09 19:00:00   0.0
  2016-01-09 20:00:00   0.0
  2016-01-09 21:00:00   0.0
  2016-01-09 22:00:00   0.0
  2016-01-09 23:00:00   0.0
  2016-01-10 00:00:00   0.0
  2016-01-10 01:00:00   0.0
  2016-01-10 02:00:00   0.0
  2016-01-10 03:00:00   0.0
  2016-01-10 04:00:00   0.0
  2016-01-10 05:00:00   0.0
  2016-01-10 06:00:00   0.0
  2016-01-10 07:00:00   0.0
  2016-01-10 08:00:00   0.0
  2016-01-10 09:00:00   0.0
  2016-01-10 10:00:00   0.0
  2016-01-10 11:00:00   0.0
  2016-01-10 12:00:00   0.0
  2016-01-10 13:00:00   0.0
  2016-01-10 14:00:00   0.0
  2016-01-10 15:00:00   0.0
  2016-01-10 16:00:00   0.0
  2016-01-10 17:00:00   0.0
  2016-01-10 18:00:00   0.0
  2016-01-10 19:00:00   0.0
  2016-01-10 20:00:00   0.0
  2016-01-10 21:00:00   0.0
  2016-01-10 22:00:00   0.0
  2016-01-10 23:00:00   0.0

  [240 rows x 1 columns]},
 ('gas',
  'pp_chp'): {'scalars': Series([], Name: 2016-01-01 00:00:00, dtype: float64), 'sequences': variable_name             flow
  2016-01-01 00:00:00  -0.000000
  2016-01-01 01:00:00  -0.000000
  2016-01-01 02:00:00  -0.000000
  2016-01-01 03:00:00  -0.000000
  2016-01-01 04:00:00  -0.000000
  2016-01-01 05:00:00   4.931668
  2016-01-01 06:00:00  10.416204
  2016-01-01 07:00:00   8.160828
  2016-01-01 08:00:00   5.623012
  2016-01-01 09:00:00   3.512637
  2016-01-01 10:00:00   1.300267
  2016-01-01 11:00:00   0.029687
  2016-01-01 12:00:00  -0.000000
  2016-01-01 13:00:00  -0.000000
  2016-01-01 14:00:00  -0.000000
  2016-01-01 15:00:00   0.426715
  2016-01-01 16:00:00   1.753438
  2016-01-01 17:00:00   3.566716
  2016-01-01 18:00:00   4.727627
  2016-01-01 19:00:00   3.374948
  2016-01-01 20:00:00   1.267700
  2016-01-01 21:00:00  -0.000000
  2016-01-01 22:00:00  -0.000000
  2016-01-01 23:00:00  -0.000000
  2016-01-02 00:00:00  -0.000000
  2016-01-02 01:00:00  -0.000000
  2016-01-02 02:00:00  -0.000000
  2016-01-02 03:00:00  -0.000000
  2016-01-02 04:00:00  -0.000000
  2016-01-02 05:00:00   5.907815
  ...                        ...
  2016-01-09 18:00:00   5.624121
  2016-01-09 19:00:00   4.531629
  2016-01-09 20:00:00   2.543400
  2016-01-09 21:00:00  -0.000000
  2016-01-09 22:00:00  -0.000000
  2016-01-09 23:00:00  -0.000000
  2016-01-10 00:00:00  -0.000000
  2016-01-10 01:00:00  -0.000000
  2016-01-10 02:00:00  -0.000000
  2016-01-10 03:00:00  -0.000000
  2016-01-10 04:00:00  -0.000000
  2016-01-10 05:00:00  -0.000000
  2016-01-10 06:00:00   2.834023
  2016-01-10 07:00:00   1.061495
  2016-01-10 08:00:00  -0.000000
  2016-01-10 09:00:00  -0.000000
  2016-01-10 10:00:00  -0.000000
  2016-01-10 11:00:00  -0.000000
  2016-01-10 12:00:00  -0.000000
  2016-01-10 13:00:00  -0.000000
  2016-01-10 14:00:00  -0.000000
  2016-01-10 15:00:00  -0.000000
  2016-01-10 16:00:00  -0.000000
  2016-01-10 17:00:00  -0.000000
  2016-01-10 18:00:00  -0.000000
  2016-01-10 19:00:00  -0.000000
  2016-01-10 20:00:00  -0.000000
  2016-01-10 21:00:00  -0.000000
  2016-01-10 22:00:00  -0.000000
  2016-01-10 23:00:00  -0.000000

  [240 rows x 1 columns]},
 ('gas',
  'pp_gas'): {'scalars': Series([], Name: 2016-01-01 00:00:00, dtype: float64), 'sequences': variable_name        flow
  2016-01-01 00:00:00   0.0
  2016-01-01 01:00:00   0.0
  2016-01-01 02:00:00   0.0
  2016-01-01 03:00:00   0.0
  2016-01-01 04:00:00   0.0
  2016-01-01 05:00:00   0.0
  2016-01-01 06:00:00   0.0
  2016-01-01 07:00:00   0.0
  2016-01-01 08:00:00   0.0
  2016-01-01 09:00:00   0.0
  2016-01-01 10:00:00   0.0
  2016-01-01 11:00:00   0.0
  2016-01-01 12:00:00   0.0
  2016-01-01 13:00:00   0.0
  2016-01-01 14:00:00   0.0
  2016-01-01 15:00:00   0.0
  2016-01-01 16:00:00   0.0
  2016-01-01 17:00:00   0.0
  2016-01-01 18:00:00   0.0
  2016-01-01 19:00:00   0.0
  2016-01-01 20:00:00   0.0
  2016-01-01 21:00:00   0.0
  2016-01-01 22:00:00   0.0
  2016-01-01 23:00:00   0.0
  2016-01-02 00:00:00   0.0
  2016-01-02 01:00:00   0.0
  2016-01-02 02:00:00   0.0
  2016-01-02 03:00:00   0.0
  2016-01-02 04:00:00   0.0
  2016-01-02 05:00:00   0.0
  ...                   ...
  2016-01-09 18:00:00   0.0
  2016-01-09 19:00:00   0.0
  2016-01-09 20:00:00   0.0
  2016-01-09 21:00:00   0.0
  2016-01-09 22:00:00   0.0
  2016-01-09 23:00:00   0.0
  2016-01-10 00:00:00   0.0
  2016-01-10 01:00:00   0.0
  2016-01-10 02:00:00   0.0
  2016-01-10 03:00:00   0.0
  2016-01-10 04:00:00   0.0
  2016-01-10 05:00:00   0.0
  2016-01-10 06:00:00   0.0
  2016-01-10 07:00:00   0.0
  2016-01-10 08:00:00   0.0
  2016-01-10 09:00:00   0.0
  2016-01-10 10:00:00   0.0
  2016-01-10 11:00:00   0.0
  2016-01-10 12:00:00   0.0
  2016-01-10 13:00:00   0.0
  2016-01-10 14:00:00   0.0
  2016-01-10 15:00:00   0.0
  2016-01-10 16:00:00   0.0
  2016-01-10 17:00:00   0.0
  2016-01-10 18:00:00   0.0
  2016-01-10 19:00:00   0.0
  2016-01-10 20:00:00   0.0
  2016-01-10 21:00:00   0.0
  2016-01-10 22:00:00   0.0
  2016-01-10 23:00:00   0.0

  [240 rows x 1 columns]},
 ('heat_pump',
  'bth'): {'scalars': Series([], Name: 2016-01-01 00:00:00, dtype: float64), 'sequences': variable_name             flow
  2016-01-01 00:00:00   5.877809
  2016-01-01 01:00:00   6.001779
  2016-01-01 02:00:00   6.277035
  2016-01-01 03:00:00   6.962015
  2016-01-01 04:00:00   8.700547
  2016-01-01 05:00:00  10.000000
  2016-01-01 06:00:00  10.000000
  2016-01-01 07:00:00  10.000000
  2016-01-01 08:00:00  10.000000
  2016-01-01 09:00:00  10.000000
  2016-01-01 10:00:00  10.000000
  2016-01-01 11:00:00  10.000000
  2016-01-01 12:00:00   9.743609
  2016-01-01 13:00:00   9.749326
  2016-01-01 14:00:00   9.871130
  2016-01-01 15:00:00  10.000000
  2016-01-01 16:00:00  10.000000
  2016-01-01 17:00:00  10.000000
  2016-01-01 18:00:00  10.000000
  2016-01-01 19:00:00  10.000000
  2016-01-01 20:00:00  10.000000
  2016-01-01 21:00:00   8.738718
  2016-01-01 22:00:00   6.028911
  2016-01-01 23:00:00   5.766941
  2016-01-02 00:00:00   6.910401
  2016-01-02 01:00:00   7.097944
  2016-01-02 02:00:00   7.399076
  2016-01-02 03:00:00   7.935088
  2016-01-02 04:00:00   9.337345
  2016-01-02 05:00:00  10.000000
  ...                        ...
  2016-01-09 18:00:00  10.000000
  2016-01-09 19:00:00  10.000000
  2016-01-09 20:00:00  10.000000
  2016-01-09 21:00:00   9.439357
  2016-01-09 22:00:00   6.774588
  2016-01-09 23:00:00   6.502866
  2016-01-10 00:00:00   4.619441
  2016-01-10 01:00:00   4.716870
  2016-01-10 02:00:00   4.933197
  2016-01-10 03:00:00   5.471532
  2016-01-10 04:00:00   6.837865
  2016-01-10 05:00:00   9.409464
  2016-01-10 06:00:00  10.000000
  2016-01-10 07:00:00  10.000000
  2016-01-10 08:00:00   9.626798
  2016-01-10 09:00:00   8.963370
  2016-01-10 10:00:00   8.267879
  2016-01-10 11:00:00   7.868453
  2016-01-10 12:00:00   7.657620
  2016-01-10 13:00:00   7.662113
  2016-01-10 14:00:00   7.757840
  2016-01-10 15:00:00   7.993265
  2016-01-10 16:00:00   8.410340
  2016-01-10 17:00:00   8.980371
  2016-01-10 18:00:00   9.345320
  2016-01-10 19:00:00   8.920086
  2016-01-10 20:00:00   8.257641
  2016-01-10 21:00:00   6.867864
  2016-01-10 22:00:00   4.738194
  2016-01-10 23:00:00   4.532308

  [240 rows x 1 columns]},
 ('heat_source',
  'b_heat_source'): {'scalars': Series([], Name: 2016-01-01 00:00:00, dtype: float64), 'sequences': variable_name            flow
  2016-01-01 00:00:00  3.918540
  2016-01-01 01:00:00  4.001186
  2016-01-01 02:00:00  4.184690
  2016-01-01 03:00:00  4.641344
  2016-01-01 04:00:00  5.800365
  2016-01-01 05:00:00  6.666667
  2016-01-01 06:00:00  6.666667
  2016-01-01 07:00:00  6.666667
  2016-01-01 08:00:00  6.666667
  2016-01-01 09:00:00  6.666667
  2016-01-01 10:00:00  6.666667
  2016-01-01 11:00:00  6.666667
  2016-01-01 12:00:00  6.495739
  2016-01-01 13:00:00  6.499551
  2016-01-01 14:00:00  6.580753
  2016-01-01 15:00:00  6.666667
  2016-01-01 16:00:00  6.666667
  2016-01-01 17:00:00  6.666667
  2016-01-01 18:00:00  6.666667
  2016-01-01 19:00:00  6.666667
  2016-01-01 20:00:00  6.666667
  2016-01-01 21:00:00  5.825812
  2016-01-01 22:00:00  4.019274
  2016-01-01 23:00:00  3.844627
  2016-01-02 00:00:00  4.606934
  2016-01-02 01:00:00  4.731963
  2016-01-02 02:00:00  4.932717
  2016-01-02 03:00:00  5.290059
  2016-01-02 04:00:00  6.224897
  2016-01-02 05:00:00  6.666667
  ...                       ...

In [15]:
all_scalars = [value['scalars'] for (key, value) in string_results.items()]
all_scalars = pd.DataFrame(all_scalars).T
tuples = [key for (key, value) in string_results.items()]
multi_index = pd.MultiIndex.from_tuples(tuples, names=['from', 'to'])
all_scalars.columns = multi_index
all_scalars

from   b_heat_source       bel                           bth    coal    gas  \
to         heat_pump demand_el excess_el heat_pump demand_th pp_coal pp_chp
invest           NaN       NaN       NaN       NaN       NaN     NaN    NaN

from          heat_pump   heat_source lignite    oil pp_chp     pp_coal  \
to     pp_gas       bth b_heat_source  pp_lig pp_oil    bel bth     bel
invest    NaN       NaN           NaN     NaN    NaN    NaN NaN     NaN

from   pp_gas pp_lig     pp_oil  pv wind
to        bel    bel        bel bel  bel
invest    NaN    NaN  80.401829 NaN  NaN

# All parameters

Open questions:
* What about node attributes, e.g. conversion_factors?
* Why does the label appear?

In [16]:
param = energysystem.results['param']
string_param = outputlib.processing.convert_keys_to_strings(param)
string_param

{('coal',
  'pp_coal'): {'scalars': fixed                                                                  False
  label                      EdgeLabel(input="<oemof.solph.network.Bus: 'co...
  max                                                                        1
  min                                                                        0
  negative_gradient_costs                                                    0
  positive_gradient_costs                                                    0
  variable_costs                                                             0
  dtype: object, 'sequences': Empty DataFrame
  Columns: []
  Index: []},
 ('gas',
  'pp_gas'): {'scalars': fixed                                                                  False
  label                      EdgeLabel(input="<oemof.solph.network.Bus: 'ga...
  max                                                                        1
  min                                                                        0
  negative_gradient_costs                                                    0
  positive_gradient_costs                                                    0
  variable_costs                                                             0
  dtype: object, 'sequences': Empty DataFrame
  Columns: []
  Index: []},
 ('gas',
  'pp_chp'): {'scalars': fixed                                                                  False
  label                      EdgeLabel(input="<oemof.solph.network.Bus: 'ga...
  max                                                                        1
  min                                                                        0
  negative_gradient_costs                                                    0
  positive_gradient_costs                                                    0
  variable_costs                                                             0
  dtype: object, 'sequences': Empty DataFrame
  Columns: []
  Index: []},
 ('oil',
  'pp_oil'): {'scalars': fixed                                                                  False
  label                      EdgeLabel(input="<oemof.solph.network.Bus: 'oi...
  max                                                                        1
  min                                                                        0
  negative_gradient_costs                                                    0
  positive_gradient_costs                                                    0
  variable_costs                                                             0
  dtype: object, 'sequences': Empty DataFrame
  Columns: []
  Index: []},
 ('lignite',
  'pp_lig'): {'scalars': fixed                                                                  False
  label                      EdgeLabel(input="<oemof.solph.network.Bus: 'li...
  max                                                                        1
  min                                                                        0
  negative_gradient_costs                                                    0
  positive_gradient_costs                                                    0
  variable_costs                                                             0
  dtype: object, 'sequences': Empty DataFrame
  Columns: []
  Index: []},
 ('bel',
  'excess_el'): {'scalars': fixed                                                                  False
  label                      EdgeLabel(input="<oemof.solph.network.Bus: 'be...
  max                                                                        1
  min                                                                        0
  negative_gradient_costs                                                    0
  positive_gradient_costs                                                    0
  variable_costs                                                             0
  dtype: object, 'sequences': Empty DataFrame
  Columns: []
  Index: []},
 ('bel',
  'demand_el'): {'scalars': fixed                                                                   True
  nominal_value                                                             85
  label                      EdgeLabel(input="<oemof.solph.network.Bus: 'be...
  max                                                                        1
  min                                                                        0
  negative_gradient_costs                                                    0
  positive_gradient_costs                                                    0
  variable_costs                                                             0
  dtype: object, 'sequences':       actual_value
  0         0.613761
  1         0.613761
  2         0.557561
  3         0.531738
  4         0.519880
  5         0.498794
  6         0.459676
  7         0.456313
  8         0.465400
  9         0.494995
  10        0.527195
  11        0.567340
  12        0.578916
  13        0.567468
  14        0.563028
  15        0.563695
  16        0.601658
  17        0.663172
  18        0.679355
  19        0.668947
  20        0.645396
  21        0.644383
  22        0.659167
  23        0.616674
  24        0.577402
  25        0.555956
  26        0.543225
  27        0.538014
  28        0.547974
  29        0.572422
  ...            ...
  8730      0.770785
  8731      0.742524
  8732      0.706242
  8733      0.691111
  8734      0.702238
  8735      0.667689
  8736      0.628879
  8737      0.590185
  8738      0.567289
  8739      0.561706
  8740      0.556251
  8741      0.545843
  8742      0.522934
  8743      0.541377
  8744      0.571036
  8745      0.602428
  8746      0.627583
  8747      0.654842
  8748      0.657640
  8749      0.643369
  8750      0.622783
  8751      0.617739
  8752      0.652930
  8753      0.707205
  8754      0.700916
  8755      0.662016
  8756      0.620588
  8757      0.618137
  8758      0.634321
  8759      0.613966

  [8760 rows x 1 columns]},
 ('bel',
  'heat_pump'): {'scalars': fixed                                                                  False
  label                      EdgeLabel(input="<oemof.solph.network.Bus: 'be...
  max                                                                        1
  min                                                                        0
  negative_gradient_costs                                                    0
  positive_gradient_costs                                                    0
  variable_costs                                                             0
  dtype: object, 'sequences': Empty DataFrame
  Columns: []
  Index: []},
 ('bth',
  'demand_th'): {'scalars': fixed                                                                   True
  nominal_value                                                             40
  label                      EdgeLabel(input="<oemof.solph.network.Bus: 'bt...
  max                                                                        1
  min                                                                        0
  negative_gradient_costs                                                    0
  positive_gradient_costs                                                    0
  variable_costs                                                             0
  dtype: object, 'sequences':       actual_value
  0         0.146945
  1         0.150044
  2         0.156926
  3         0.174050
  4         0.217514
  5         0.299317
  6         0.354162
  7         0.331608
  8         0.306230
  9         0.285126
  10        0.263003
  11        0.250297
  12        0.243590
  13        0.243733
  14        0.246778
  15        0.254267
  16        0.267534
  17        0.285667
  18        0.297276
  19        0.283749
  20        0.262677
  21        0.218468
  22        0.150723
  23        0.144174
  24        0.172760
  25        0.177449
  26        0.184977
  27        0.198377
  28        0.233434
  29        0.309078
  ...            ...
  8730      0.319494
  8731      0.308096
  8732      0.287353
  8733      0.246196
  8734      0.176694
  8735      0.169607
  8736      0.179479
  8737      0.184350
  8738      0.192171
  8739      0.206093
  8740      0.242512
  8741      0.321099
  8742      0.376240
  8743      0.363225
  8744      0.342119
  8745      0.323363
  8746      0.300262
  8747      0.286402
  8748      0.277603
  8749      0.276330
  8750      0.280676
  8751      0.290193
  8752      0.300801
  8753      0.317976
  8754      0.331919
  8755      0.320078
  8756      0.298529
  8757      0.255771
  8758      0.183566
  8759      0.176203

  [8760 rows x 1 columns]},
 ('wind',
  'bel'): {'scalars': fixed                                                                   True
  nominal_value                                                           66.3
  label                      EdgeLabel(input="<oemof.solph.network.Source: ...
  max                                                                        1
  min                                                                        0
  negative_gradient_costs                                                    0
  positive_gradient_costs                                                    0
  variable_costs                                                             0
  dtype: object, 'sequences':       actual_value
  0           0.2780
  1           0.2810
  2           0.2830
  3           0.2830
  4           0.2520
  5           0.1860
  6           0.1860
  7           0.1850
  8           0.1850
  9           0.1850
  10          0.5140
  11          0.5140
  12          0.5130
  13          0.6530
  14          0.7880
  15          0.7870
  16          0.9320
  17          0.9900
  18          0.8730
  19          0.9300
  20          0.9290
  21          0.9880
  22          1.0000
  23          0.9270
  24          0.9840
  25          0.9950
  26          0.9810
  27          0.9680
  28          0.9960
  29          0.8680
  ...            ...
  8730        0.0822
  8731        0.0822
  8732        0.0296
  8733        0.0296
  8734        0.0824
  8735        0.0830
  8736        0.0828
  8737        0.0827
  8738        0.1870
  8739        0.0822
  8740        0.1860
  8741        0.1850
  8742        0.0817
  8743        0.1840
  8744        0.0812
  8745        0.0810
  8746        0.0289
  8747        0.0800
  8748        0.0286
  8749        0.0285
  8750        0.0789
  8751        0.0788
  8752        0.3180
  8753        0.1780
  8754        0.3170
  8755        0.2540
  8756        0.2840
  8757        0.2840
  8758        0.2860
  8759        0.2590

  [8760 rows x 1 columns]},
 ('pv',
  'bel'): {'scalars': fixed                                                                   True
  nominal_value                                                           65.3
  label                      EdgeLabel(input="<oemof.solph.network.Source: ...
  max                                                                        1
  min                                                                        0
  negative_gradient_costs                                                    0
  positive_gradient_costs                                                    0
  variable_costs                                                             0
  dtype: object, 'sequences':       actual_value
  0          0.00000
  1          0.00000
  2          0.00000
  3          0.00000
  4          0.00000
  5          0.00000
  6          0.00000
  7          0.00000
  8          0.00910
  9          0.03640
  10         0.05710
  11         0.07610
  12         0.03470
  13         0.02730
  14         0.02070
  15         0.00496
  16         0.00000
  17         0.00000
  18         0.00000
  19         0.00000
  20         0.00000
  21         0.00000
  22         0.00000
  23         0.00000
  24         0.00000
  25         0.00000
  26         0.00000
  27         0.00000
  28         0.00000
  29         0.00000
  ...            ...
  8730       0.00000
  8731       0.00000
  8732       0.00000
  8733       0.00000
  8734       0.00000
  8735       0.00000
  8736       0.00000
  8737       0.00000
  8738       0.00000
  8739       0.00000
  8740       0.00000
  8741       0.00000
  8742       0.00000
  8743       0.00000
  8744       0.00496
  8745       0.02730
  8746       0.04630
  8747       0.03890
  8748       0.03470
  8749       0.05290
  8750       0.03230
  8751       0.02080
  8752       0.00000
  8753       0.00000
  8754       0.00000
  8755       0.00000
  8756       0.00000
  8757       0.00000
  8758       0.00000
  8759       0.00000

  [8760 rows x 1 columns]},
 ('pp_coal',
  'bel'): {'scalars': fixed                                                                  False
  nominal_value                                                           20.2
  label                      EdgeLabel(input="<oemof.solph.network.Transfor...
  max                                                                        1
  min                                                                        0
  negative_gradient_costs                                                    0
  positive_gradient_costs                                                    0
  variable_costs                                                            25
  dtype: object, 'sequences': Empty DataFrame
  Columns: []
  Index: []},
 ('pp_lig',
  'bel'): {'scalars': fixed                                                                  False
  nominal_value                                                           11.8
  label                      EdgeLabel(input="<oemof.solph.network.Transfor...
  max                                                                        1
  min                                                                        0
  negative_gradient_costs                                                    0
  positive_gradient_costs                                                    0
  variable_costs                                                            19
  dtype: object, 'sequences': Empty DataFrame
  Columns: []
  Index: []},
 ('pp_gas',
  'bel'): {'scalars': fixed                                                                  False
  nominal_value                                                             41
  label                      EdgeLabel(input="<oemof.solph.network.Transfor...
  max                                                                        1
  min                                                                        0
  negative_gradient_costs                                                    0
  positive_gradient_costs                                                    0
  variable_costs                                                            40
  dtype: object, 'sequences': Empty DataFrame
  Columns: []
  Index: []},
 ('pp_oil',
  'bel'): {'scalars': fixed                                                                  False
  investment_ep_costs                                                  80.2426
  investment_existing                                                        0
  investment_maximum                                                       100
  investment_minimum                                                         0
  label                      EdgeLabel(input="<oemof.solph.network.Transfor...
  max                                                                        1
  min                                                                        0
  negative_gradient_costs                                                    0
  positive_gradient_costs                                                    0
  variable_costs                                                             0
  dtype: object, 'sequences': Empty DataFrame
  Columns: []
  Index: []},
 ('pp_chp',
  'bel'): {'scalars': fixed                                                                  False
  nominal_value                                                             30
  label                      EdgeLabel(input="<oemof.solph.network.Transfor...
  max                                                                        1
  min                                                                        0
  negative_gradient_costs                                                    0
  positive_gradient_costs                                                    0
  variable_costs                                                            42
  dtype: object, 'sequences': Empty DataFrame
  Columns: []
  Index: []},
 ('pp_chp',
  'bth'): {'scalars': fixed                                                                  False
  nominal_value                                                             40
  label                      EdgeLabel(input="<oemof.solph.network.Transfor...
  max                                                                        1
  min                                                                        0
  negative_gradient_costs                                                    0
  positive_gradient_costs                                                    0
  variable_costs                                                             0
  dtype: object, 'sequences': Empty DataFrame
  Columns: []
  Index: []},
 ('b_heat_source',
  'heat_pump'): {'scalars': fixed                                                                  False
  label                      EdgeLabel(input="<oemof.solph.network.Bus: 'b_...
  max                                                                        1
  min                                                                        0
  negative_gradient_costs                                                    0
  positive_gradient_costs                                                    0
  variable_costs                                                             0
  dtype: object, 'sequences': Empty DataFrame
  Columns: []
  Index: []},
 ('heat_source',
  'b_heat_source'): {'scalars': fixed                                                                  False
  label                      EdgeLabel(input="<oemof.solph.network.Source: ...
  max                                                                        1
  min                                                                        0
  negative_gradient_costs                                                    0
  positive_gradient_costs                                                    0
  variable_costs                                                             0
  dtype: object, 'sequences': Empty DataFrame
  Columns: []
  Index: []},
 ('heat_pump',
  'bth'): {'scalars': fixed                                                                  False
  nominal_value                                                             10
  label                      EdgeLabel(input="<oemof.solph.network.Transfor...
  max                                                                        1
  min                                                                        0
  negative_gradient_costs                                                    0
  positive_gradient_costs                                                    0
  variable_costs                                                             0
  dtype: object, 'sequences': Empty DataFrame
  Columns: []
  Index: []},
 ('coal', 'None'): {'scalars': balanced    False
  label        coal
  dtype: object, 'sequences': Empty DataFrame
  Columns: []
  Index: []},
 ('gas', 'None'): {'scalars': balanced    False
  label         gas
  dtype: object, 'sequences': Empty DataFrame
  Columns: []
  Index: []},
 ('oil', 'None'): {'scalars': balanced    False
  label         oil
  dtype: object, 'sequences': Empty DataFrame
  Columns: []
  Index: []},
 ('lignite', 'None'): {'scalars': balanced      False
  label       lignite

In [17]:
all_sequences_param = [value['sequences'].rename(columns={'actual_value': key}) for (key, value) in string_param.items() if value['sequences'].empty == False]

all_sequences_param = pd.concat(all_sequences_param, axis=1)
tuples = [key for (key, value) in all_sequences_param.items()]
tuples

multi_index = pd.MultiIndex.from_tuples(tuples, names=['from', 'to'])
multi_index

all_sequences_param.columns = multi_index
all_sequences_param.head()

from       bel       bth   wind   pv
to   demand_el demand_th    bel  bel
0     0.613761  0.146945  0.278  0.0
1     0.613761  0.150044  0.281  0.0
2     0.557561  0.156926  0.283  0.0
3     0.531738  0.174050  0.283  0.0
4     0.519880  0.217514  0.252  0.0

TODO: what about the label?

In [18]:
all_scalars_param = [value['scalars'].rename(columns={'actual_value': key}) for (key, value) in string_param.items() if value['sequences'].empty == False]
all_scalars_param = pd.DataFrame(all_scalars_param)
# tuples = [key for (key, value) in all_scalars_param.items()]
# print(tuples)
# multi_index = pd.MultiIndex.from_tuples(tuples, names=['from', 'to'])
# all_scalars_param.columns = multi_index
all_scalars_param

,fixed,nominal_value,label,max,min,negative_gradient_costs,positive_gradient_costs,variable_costs
0,True,85.0,"EdgeLabel(input=""<oemof.solph.network.Bus: 'be...",1,0,0,0,0
1,True,40.0,"EdgeLabel(input=""<oemof.solph.network.Bus: 'bt...",1,0,0,0,0
2,True,66.3,"EdgeLabel(input=""<oemof.solph.network.Source: ...",1,0,0,0,0
3,True,65.3,"EdgeLabel(input=""<oemof.solph.network.Source: ...",1,0,0,0,0

# Xarray

## DataArray
http://xarray.pydata.org/en/stable/data-structures.html#dataarray


* data: a multi-dimensional array of values (e.g., a numpy ndarray, Series, DataFrame or Panel)
* coords: a list or dictionary of coordinates. If a list, it should be a list of tuples where the first element is the dimension name and the second element is the corresponding coordinate array_like object.
* dims: a list of dimension names. If omitted and coords is a list of tuples, dimension names are taken from coords.
* attrs: a dictionary of attributes to add to the instance
* name: a string that names the instance

In [19]:
data = np.random.rand(4, 3)
locs = ['IA', 'IL', 'IN']
times = pd.date_range('2000-01-01', periods=4)
foo = xr.DataArray(data,
                   coords=[times, locs],
                   dims=['time', 'space'],
                   attrs={'purpose': 'demonstration',
                          'occasion': 'oemof dev meeting'},
                   name='example_dataarray')
foo

<xarray.DataArray 'example_dataarray' (time: 4, space: 3)>
array([[0.074032, 0.094947, 0.570282],
       [0.366172, 0.626441, 0.799658],
       [0.362065, 0.999693, 0.98126 ],
       [0.935636, 0.818623, 0.474498]])
Coordinates:
  * time     (time) datetime64[ns] 2000-01-01 2000-01-02 2000-01-03 2000-01-04
  * space    (space) <U2 'IA' 'IL' 'IN'
Attributes:
    purpose:   demonstration
    occasion:  oemof dev meeting

## DataSet
http://xarray.pydata.org/en/stable/data-structures.html#dataset

To make an Dataset from scratch, supply dictionaries for any variables (data_vars), coordinates (coords) and attributes (attrs).

    data_vars should be a dictionary with each key as the name of the variable and each value as one of:
        A DataArray or Variable
        A tuple of the form (dims, data[, attrs]), which is converted into arguments for Variable
        A pandas object, which is converted into a DataArray
        A 1D array or list, which is interpreted as values for a one dimensional coordinate variable along the same dimension as it’s name
    coords should be a dictionary of the same form as data_vars.
    attrs should be a dictionary.

In [33]:
temp = 15 + 8 * np.random.randn(2, 2, 10)

precip = 10 * np.random.rand(2, 2, 10)

lon = [[-99.83, -99.32], [-99.79, -99.23]]
lat = [[42.25, 42.21], [42.63, 42.59]]

# for real use cases, its good practice to supply array attributes such as
# units, but we won't bother here for the sake of brevity
ds = xr.Dataset({'temperature': (['x', 'y', 'time'],  temp),
                 'precipitation': (['x', 'y', 'time'], precip)},
                 coords={'lon': (['x', 'y'], lon),
                         'lat': (['x', 'y'], lat),
                         'time': pd.date_range('2014-09-06', periods=10),
                         'reference_time': pd.Timestamp('2014-09-05')})

ds

<xarray.Dataset>
Dimensions:         (time: 10, x: 2, y: 2)
Coordinates:
    lon             (x, y) float64 -99.83 -99.32 -99.79 -99.23
    lat             (x, y) float64 42.25 42.21 42.63 42.59
  * time            (time) datetime64[ns] 2014-09-06 2014-09-07 ... 2014-09-15
    reference_time  datetime64[ns] 2014-09-05
Dimensions without coordinates: x, y
Data variables:
    temperature     (x, y, time) float64 8.507 15.58 16.93 ... 17.88 12.96 15.93
    precipitation   (x, y, time) float64 2.533 6.339 0.04154 ... 3.287 9.265

## Test: save results as xarray DataArrays / DataSets

In [25]:
seq = all_sequences.unstack()
seq.index.names = ['from', 'to', 'time']
# seq

In [29]:
dataarray = xr.DataArray.from_series(seq)
dataarray

<xarray.DataArray (from: 16, to: 12, time: 240)>
array([[[        nan,         nan, ...,         nan,         nan],
        [        nan,         nan, ...,         nan,         nan],
        ...,
        [        nan,         nan, ...,         nan,         nan],
        [        nan,         nan, ...,         nan,         nan]],

       [[        nan,         nan, ...,         nan,         nan],
        [        nan,         nan, ...,         nan,         nan],
        ...,
        [        nan,         nan, ...,         nan,         nan],
        [        nan,         nan, ...,         nan,         nan]],

       ...,

       [[        nan,         nan, ...,         nan,         nan],
        [0.00000e+00, 0.00000e+00, ..., 0.00000e+00, 0.00000e+00],
        ...,
        [        nan,         nan, ...,         nan,         nan],
        [        nan,         nan, ...,         nan,         nan]],

       [[        nan,         nan, ...,         nan,         nan],
        [1.84314e+01, 1.86303e+01, ..., 9.54720e-03, 9.54720e-03],
        ...,
        [        nan,         nan, ...,         nan,         nan],
        [        nan,         nan, ...,         nan,         nan]]])
Coordinates:
  * from     (from) object 'b_heat_source' 'bel' 'bth' ... 'pp_oil' 'pv' 'wind'
  * to       (to) object 'b_heat_source' 'bel' 'bth' ... 'pp_lig' 'pp_oil'
  * time     (time) datetime64[ns] 2016-01-01 ... 2016-01-10T23:00:00

In [24]:
lon = [[-99.83, -99.32], [-99.79, -99.23]]
lat = [[42.25, 42.21], [42.63, 42.59]]

# for real use cases, its good practice to supply array attributes such as
# units, but we won't bother here for the sake of brevity
ds = xr.Dataset({'sequences': (['from', 'to', 'time'],  temp),
                 'scalars': (['from', 'to', 'time'], precip)},
                 coords={'lon': (['x', 'y'], lon),
                         'lat': (['x', 'y'], lat),
                         'time': pd.date_range('2014-09-06', periods=3),
                         'reference_time': pd.Timestamp('2014-09-05')})

ds

<xarray.Dataset>
Dimensions:         (from: 2, time: 3, to: 2, x: 2, y: 2)
Coordinates:
    lon             (x, y) float64 -99.83 -99.32 -99.79 -99.23
    lat             (x, y) float64 42.25 42.21 42.63 42.59
  * time            (time) datetime64[ns] 2014-09-06 2014-09-07 2014-09-08
    reference_time  datetime64[ns] 2014-09-05
Dimensions without coordinates: from, to, x, y
Data variables:
    sequences       (from, to, time) float64 12.32 18.74 3.195 ... 16.34 21.88
    scalars         (from, to, time) float64 0.3475 7.038 1.598 ... 5.112 2.741